### ISSUE TITLE
CPAN Pull request challenge update test suite 

### ISSUE THREAD

**Issue by sdeseille** [und3f/anyevent-ping#7]
Hi Sergii

I joined the "CPAN Pull Request Challenge" and Neil Bowers ask me to make a Pull Request on your module "AnyEvent::Ping".

I work on Win32 system and see that test suite have some errors.

Will you accept that i submit a patch in order to the test suite work also on Win32 system ?
I already found what i have to modify.

regards

sdeseille

**Comment by und3f** [comment]
Hi Sebastien

Yes, I will accept a patch. 

I didn't investigate problem with Win32, I just think that some socket magic needed to run module under Win32 (as the raw socket is used). Anyway it is up to you, I'll wait for a patch.

Thank you for choosing AE::Ping!

**Comment by und3f** [comment]
CPAN testers reports about passed tests on Win32.
